from django.urls import path
from .view_modules.api.eventbrite_views import (
    create_event,
    update_event,
    delete_event,
    publish_event,
    unpublish_event,
    connection,
    events_list,
    events_list_public,
)
from .view_modules.soft_delete_entity_views import (
    AdminClubDeactivateView,
    AdminClubActivateView,
    AdminClubMemberDeactivateView,
    AdminEventDeactivateView,
    AdminEventActivateView,
    AdminNewsDeactivateView,
    AdminNewsActivateView,
    AdminBookDeactivateView,
    AdminBookActivateView,
    AdminSessionDeactivateView,
    AdminSessionActivateView,
)
from .views import (
    AdminBookDetailView,
    AdminBookBulkDeleteView,
    AdminBookListCreateView,
    AdminAuditLogListView,
    AdminActivityLogListView,
    AdminDashboardNotificationsView,
    AdminDashboardSummaryView,
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    AdminClubDetailView,
    AdminClubListCreateView,
    AdminClubMemberAssignView,
    AdminClubMemberRemoveView,
    AdminContentDetailView,
    AdminContentListCreateView,
    AdminEventbriteConnectionView,
    AdminEventDetailView,
    AdminEventEventbriteAttendeesView,
    AdminEventEventbriteDetailView,
    AdminEventEventbriteOrdersView,
    AdminEventEventbriteSyncView,
    AdminEventEventbriteTicketClassView,
    AdminEventSeatingView,
    AdminEventSeatingPaintView,
    AdminEventSeatingSyncView,
    AdminEventBulkDeleteView,
    AdminEventBulkStatusUpdateView,
    AdminEventListCreateView,
    AdminImageUploadView,
    AdminMetricsOverviewView,
    AdminNewsDetailView,
    AdminNewsBulkDeleteView,
    AdminNewsBulkStatusUpdateView,
    AdminNewsListCreateView,
    AdminNewsStatusListView,
    AdminPhotoCarouselDetailView,
    AdminPhotoCarouselListCreateView,
    AdminNewsletterDetailView,
    AdminNewsletterListCreateView,
    AdminNewsletterSendView,
    AdminNewsletterSubscriberDetailView,
    AdminNewsletterSubscriberListCreateView,
    AdminRegistrationListView,
    AdminRegistrationBulkStatusUpdateView,
    AdminRegistrationStatusListView,
    AdminRegistrationStatusUpdateView,
    AdminRoleListView,
    AdminSessionDetailView,
    AdminSessionListCreateView,
    AdminUserDeactivateView,
    AdminUserActivateView,
    AdminUserDetailView,
    AdminUserListCreateView,
    LoginView,
    LogoutView,
    PublicBookDetailView,
    PublicBookListView,
    PublicCategoryListView,
    MeView,
    PublicClubDetailView,
    PublicClubRegistrationCreateView,
    PublicClubListView,
    PublicContentListView,
    PublicEventDetailView,
    PublicEventCalendarView,
    PublicEventListView,
    PublicEventRegistrationCreateView,
    PublicNewsDetailView,
    PublicNewsListView,
    PublicNewsStatusListView,
    PublicPhotoCarouselListView,
    PublicSessionCalendarView,
    PublicSessionDetailView,
    PublicSessionListView,
    PublicSessionRegistrationCreateView,
    RefreshTokenView,
    TrackMetricView,
    UniversitySearchView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/refresh/', RefreshTokenView.as_view(), name='auth-refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('auth/me/', MeView.as_view(), name='auth-me'),
    path('auth/roles/', AdminRoleListView.as_view(), name='auth-roles'),
    path('auth/users/', AdminUserListCreateView.as_view(), name='auth-users'),
    path('auth/users/<int:pk>/', AdminUserDetailView.as_view(), name='auth-user-detail'),
    path('auth/users/<int:pk>/deactivate/', AdminUserDeactivateView.as_view(), name='auth-user-deactivate'),
    path('auth/users/<int:pk>/activate/', AdminUserActivateView.as_view(), name='auth-user-activate'),
    path('clubs/', PublicClubListView.as_view(), name='clubs-public-list'),
    path('clubs/<int:pk>/', PublicClubDetailView.as_view(), name='clubs-public-detail'),
    path(
        'clubs/<int:pk>/registrations/',
        PublicClubRegistrationCreateView.as_view(),
        name='clubs-public-registration-create',
    ),
    path('news/statuses/', PublicNewsStatusListView.as_view(), name='news-statuses-public-list'),
    path('news/', PublicNewsListView.as_view(), name='news-public-list'),
    path('news/<int:pk>/', PublicNewsDetailView.as_view(), name='news-public-detail'),
    path('books/', PublicBookListView.as_view(), name='books-public-list'),
    path('books/<int:pk>/', PublicBookDetailView.as_view(), name='books-public-detail'),
    path('categories/', PublicCategoryListView.as_view(), name='categories-public-list'),
    path('sessions/', PublicSessionListView.as_view(), name='sessions-public-list'),
    path('sessions/<int:pk>/', PublicSessionDetailView.as_view(), name='sessions-public-detail'),
    path(
        'sessions/<int:pk>/registrations/',
        PublicSessionRegistrationCreateView.as_view(),
        name='sessions-public-registration-create',
    ),
    path(
        'sessions/<int:pk>/calendar/',
        PublicSessionCalendarView.as_view(),
        name='sessions-public-calendar',
    ),
    path('events/', PublicEventListView.as_view(), name='events-public-list'),
    path('events/<int:pk>/', PublicEventDetailView.as_view(), name='events-public-detail'),
    path(
        'events/<int:pk>/registrations/',
        PublicEventRegistrationCreateView.as_view(),
        name='events-public-registration-create',
    ),
    path(
        'events/<int:pk>/calendar/',
        PublicEventCalendarView.as_view(),
        name='events-public-calendar',
    ),
    # Simple Event endpoints that sync with Eventbrite
    path('content/', PublicContentListView.as_view(), name='content-public-list'),
    path('photos/', PublicPhotoCarouselListView.as_view(), name='photos-public-list'),
    path('metrics/view/', TrackMetricView.as_view(), name='metrics-public-view'),
    path('universities/search/', UniversitySearchView.as_view(), name='universities-search'),
    path('content/admin/', AdminContentListCreateView.as_view(), name='content-admin-list-create'),
    path('content/admin/<uuid:pk>/', AdminContentDetailView.as_view(), name='content-admin-detail'),
    path('photos/admin/', AdminPhotoCarouselListCreateView.as_view(), name='photos-admin-list-create'),
    path('photos/admin/<uuid:pk>/', AdminPhotoCarouselDetailView.as_view(), name='photos-admin-detail'),
    path('uploads/images/', AdminImageUploadView.as_view(), name='uploads-image-create'),
    path('dashboard/admin/', AdminDashboardSummaryView.as_view(), name='dashboard-admin-summary'),
    path('metrics/admin/', AdminMetricsOverviewView.as_view(), name='metrics-admin-overview'),
    path('dashboard/admin/audit/', AdminAuditLogListView.as_view(), name='dashboard-admin-audit'),
    path('dashboard/admin/logs/', AdminActivityLogListView.as_view(), name='dashboard-admin-logs'),
    path(
        'dashboard/admin/notifications/',
        AdminDashboardNotificationsView.as_view(),
        name='dashboard-admin-notifications',
    ),
    path('news/admin/statuses/', AdminNewsStatusListView.as_view(), name='news-statuses-admin-list'),
    path('news/admin/bulk-delete/', AdminNewsBulkDeleteView.as_view(), name='news-admin-bulk-delete'),
    path('news/admin/bulk-status/', AdminNewsBulkStatusUpdateView.as_view(), name='news-admin-bulk-status'),
    path('news/admin/', AdminNewsListCreateView.as_view(), name='news-admin-list-create'),
    path('news/admin/<int:pk>/', AdminNewsDetailView.as_view(), name='news-admin-detail'),
    path('news/admin/<int:pk>/deactivate/', AdminNewsDeactivateView.as_view(), name='news-admin-deactivate'),
    path('news/admin/<int:pk>/activate/', AdminNewsActivateView.as_view(), name='news-admin-activate'),
    path('newsletters/admin/', AdminNewsletterListCreateView.as_view(), name='newsletters-admin-list-create'),
    path(
        'newsletters/admin/<int:pk>/',
        AdminNewsletterDetailView.as_view(),
        name='newsletters-admin-detail',
    ),
    path(
        'newsletters/admin/<int:pk>/send/',
        AdminNewsletterSendView.as_view(),
        name='newsletters-admin-send',
    ),
    path(
        'newsletters/admin/subscribers/',
        AdminNewsletterSubscriberListCreateView.as_view(),
        name='newsletters-admin-subscribers-list-create',
    ),
    path(
        'newsletters/admin/subscribers/<int:pk>/',
        AdminNewsletterSubscriberDetailView.as_view(),
        name='newsletters-admin-subscriber-detail',
    ),
    path('books/admin/bulk-delete/', AdminBookBulkDeleteView.as_view(), name='books-admin-bulk-delete'),
    path('books/admin/', AdminBookListCreateView.as_view(), name='books-admin-list-create'),
    path('books/admin/<int:pk>/', AdminBookDetailView.as_view(), name='books-admin-detail'),
    path('books/admin/<int:pk>/deactivate/', AdminBookDeactivateView.as_view(), name='books-admin-deactivate'),
    path('books/admin/<int:pk>/activate/', AdminBookActivateView.as_view(), name='books-admin-activate'),
    path('sessions/admin/', AdminSessionListCreateView.as_view(), name='sessions-admin-list-create'),
    path('sessions/admin/<int:pk>/', AdminSessionDetailView.as_view(), name='sessions-admin-detail'),
    path('sessions/admin/<int:pk>/deactivate/', AdminSessionDeactivateView.as_view(), name='sessions-admin-deactivate'),
    path('sessions/admin/<int:pk>/activate/', AdminSessionActivateView.as_view(), name='sessions-admin-activate'),
    path('events/admin/', AdminEventListCreateView.as_view(), name='events-admin-list-create'),
    # Eventbrite action endpoints
    path('events/admin/eventbrite/create/', create_event, name='events-admin-eventbrite-create'),
    path('events/admin/eventbrite/connection/', AdminEventbriteConnectionView.as_view(), name='events-admin-eventbrite-connection'),
    path('events/admin/eventbrite/<int:pk>/update/', update_event, name='events-admin-eventbrite-update'),
    path('events/admin/eventbrite/<int:pk>/delete/', delete_event, name='events-admin-eventbrite-delete'),
    path('events/admin/eventbrite/<int:pk>/publish/', publish_event, name='events-admin-eventbrite-publish'),
    path('events/admin/eventbrite/<int:pk>/unpublish/', unpublish_event, name='events-admin-eventbrite-unpublish'),
    path('events/admin/bulk-delete/', AdminEventBulkDeleteView.as_view(), name='events-admin-bulk-delete'),
    path('events/admin/bulk-status/', AdminEventBulkStatusUpdateView.as_view(), name='events-admin-bulk-status'),
    path('events/admin/<int:pk>/', AdminEventDetailView.as_view(), name='events-admin-detail'),
    path('events/admin/<int:pk>/eventbrite/sync/', AdminEventEventbriteSyncView.as_view(), name='events-admin-eventbrite-sync'),
    path('events/admin/<int:pk>/eventbrite/', AdminEventEventbriteDetailView.as_view(), name='events-admin-eventbrite-detail'),
    path('events/admin/<int:pk>/eventbrite/ticket-classes/', AdminEventEventbriteTicketClassView.as_view(), name='events-admin-eventbrite-ticket-classes'),
    path('events/admin/<int:pk>/eventbrite/attendees/', AdminEventEventbriteAttendeesView.as_view(), name='events-admin-eventbrite-attendees'),
    path('events/admin/<int:pk>/eventbrite/orders/', AdminEventEventbriteOrdersView.as_view(), name='events-admin-eventbrite-orders'),
    path('events/admin/<int:event_id>/seating/', AdminEventSeatingView.as_view(), name='events-admin-seating'),
    path('events/admin/<int:event_id>/seating/paint/', AdminEventSeatingPaintView.as_view(), name='events-admin-seating-paint'),
    path('events/admin/<int:event_id>/seating/sync/', AdminEventSeatingSyncView.as_view(), name='events-admin-seating-sync'),
    path('events/admin/<int:pk>/deactivate/', AdminEventDeactivateView.as_view(), name='events-admin-deactivate'),
    path('events/admin/<int:pk>/activate/', AdminEventActivateView.as_view(), name='events-admin-activate'),
    path('categories/admin/', AdminCategoryListCreateView.as_view(), name='categories-admin-list-create'),
    path('categories/admin/<int:pk>/', AdminCategoryDetailView.as_view(), name='categories-admin-detail'),
    path(
        'registrations/admin/statuses/',
        AdminRegistrationStatusListView.as_view(),
        name='registrations-admin-statuses-list',
    ),
    path(
        'registrations/admin/',
        AdminRegistrationListView.as_view(),
        name='registrations-admin-list',
    ),
    path(
        'registrations/admin/bulk-status/',
        AdminRegistrationBulkStatusUpdateView.as_view(),
        name='registrations-admin-bulk-status',
    ),
    path(
        'registrations/admin/<int:pk>/status/',
        AdminRegistrationStatusUpdateView.as_view(),
        name='registrations-admin-status-update',
    ),
    path('clubs/admin/', AdminClubListCreateView.as_view(), name='clubs-admin-list-create'),
    path('clubs/admin/<int:pk>/', AdminClubDetailView.as_view(), name='clubs-admin-detail'),
    path('clubs/admin/<int:pk>/deactivate/', AdminClubDeactivateView.as_view(), name='clubs-admin-deactivate'),
    path('clubs/admin/<int:pk>/activate/', AdminClubActivateView.as_view(), name='clubs-admin-activate'),
    path('clubs/admin/<int:pk>/members/', AdminClubMemberAssignView.as_view(), name='clubs-admin-member-assign'),
    path('clubs/admin/<int:pk>/members/<int:user_pk>/', AdminClubMemberRemoveView.as_view(), name='clubs-admin-member-remove'),
    path('clubs/admin/<int:pk>/members/<int:user_pk>/deactivate/', AdminClubMemberDeactivateView.as_view(), name='clubs-admin-member-deactivate'),
    path('clubs/admin/<int:pk>/users/<int:user_pk>/assign/', AdminClubMemberAssignView.as_view(), name='clubs-admin-user-assign-compat'),
    path('clubs/admin/<int:pk>/users/<int:user_pk>/remove/', AdminClubMemberRemoveView.as_view(), name='clubs-admin-user-remove-compat'),
    path('events/admin/eventbrite/events/', events_list, name='eventbrite-events-list'),
    path('events/eventbrite/public/', events_list_public, name='eventbrite-events-public'),
]
