# Generated by Django 5.1.6 on 2026-06-06 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocultura', '0005_add_is_active_to_content_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('content_type', models.CharField(max_length=32)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('actor_name', models.CharField(max_length=150)),
                ('metadata_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_audit_logs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(db_column='id_books', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('publication_year', models.IntegerField()),
                ('cover_image', models.CharField(blank=True, default='', max_length=500)),
                ('summary', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-is_featured', 'title', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='id_category', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'clubs_registrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EditorialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=32)),
                ('object_id', models.IntegerField()),
                ('from_status', models.CharField(blank=True, max_length=50, null=True)),
                ('to_status', models.CharField(max_length=50)),
                ('actor_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'editorial_actions',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(db_column='id_event', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('start_date', models.DateTimeField(db_column='start_date')),
                ('end_date', models.DateTimeField(db_column='end_date')),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_external', models.BooleanField(default=False)),
                ('enable_registrations', models.BooleanField(default=False)),
                ('registration_capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em Revisao'), ('published', 'Publicado'), ('active', 'Ativo'), ('completed', 'Concluido'), ('cancelled', 'Cancelado'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('eventbrite_event_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('eventbrite_url', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('eventbrite_status', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('eventbrite_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('eventbrite_last_error', models.TextField(blank=True, default=None, null=True)),
                ('eventbrite_venue_id', models.CharField(blank=True, default='', max_length=64)),
                ('eventbrite_venue', models.JSONField(blank=True, default=dict, null=True)),
                ('eventbrite_ticket_classes', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['event_date', 'start_date', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_registrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(db_column='id_news', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('image', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-published_at', '-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(db_column='id_newsletter', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.CharField(blank=True, db_column='image', default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('sent', 'Enviada'), ('cancelled', 'Cancelada')], default='draft', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'newsletters',
                'ordering': ['-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(db_column='id_newsletter_sub', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'news_letter_subscribers',
                'ordering': ['-subscribed_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsStatus',
            fields=[
                ('id', models.AutoField(db_column='id_nstatus', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'nstatus',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(db_column='id_registrations', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-created_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('id', models.AutoField(db_column='id_rstatus', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'rstatus',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(db_column='id_sessions', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('session_date', models.DateField()),
                ('start_date', models.DateTimeField(db_column='start_date')),
                ('end_date', models.DateTimeField(db_column='end_date')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluido'), ('cancelled', 'Cancelado')], default='active', max_length=16)),
                ('enable_registrations', models.BooleanField(default=False)),
                ('registration_capacity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['session_date', 'start_date', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session_registrations',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='culturalcontent',
            table='infocultura_culturalcontent',
        ),
        migrations.CreateModel(
            name='VenueLayout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('layout_mode', models.CharField(choices=[('local_layout', 'Layout Local'), ('eventbrite_reserved_seating', 'Reserved Seating Eventbrite')], default='local_layout', max_length=50)),
                ('rows', models.IntegerField(default=0)),
                ('seats_per_row', models.IntegerField(default=0)),
                ('row_prefix', models.CharField(blank=True, default='', max_length=20)),
                ('eventbrite_seat_map_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('eventbrite_source_seat_map_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_layout', to='infocultura.event')),
            ],
            options={
                'db_table': 'infocultura_venue_layout',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventSeatSyncIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventbrite_attendee_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('eventbrite_order_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('attendee_name', models.CharField(blank=True, default='', max_length=255)),
                ('attendee_email', models.CharField(blank=True, default='', max_length=255)),
                ('ticket_class_name', models.CharField(blank=True, default='', max_length=255)),
                ('issue_type', models.CharField(choices=[('unassigned', 'Sem assento atribuído'), ('duplicate', 'Participante com múltiplos assentos'), ('seat_not_found', 'Assento do Eventbrite inexistente na sala local'), ('missing_attendee_id', 'Participante sem ID da Eventbrite')], default='unassigned', max_length=30)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_issues', to='infocultura.event')),
            ],
            options={
                'db_table': 'infocultura_event_seat_sync_issue',
                'managed': True,
                'constraints': [models.UniqueConstraint(condition=models.Q(('eventbrite_attendee_id__isnull', False)), fields=('event', 'eventbrite_attendee_id'), name='unique_event_sync_issue_attendee')],
            },
        ),
        migrations.CreateModel(
            name='EventSeat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_label', models.CharField(blank=True, default='', max_length=100)),
                ('row_label', models.CharField(max_length=50)),
                ('seat_number', models.IntegerField(blank=True, null=True)),
                ('seat_label', models.CharField(max_length=100)),
                ('eventbrite_seat_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('eventbrite_attendee_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('eventbrite_order_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('attendee_name', models.CharField(blank=True, default='', max_length=255)),
                ('attendee_email', models.CharField(blank=True, default='', max_length=255)),
                ('ticket_class_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('ticket_class_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('blocked', 'Bloqueado'), ('vip', 'VIP'), ('assigned', 'Atribuído')], default='available', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='infocultura.event')),
                ('venue_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='infocultura.venuelayout')),
            ],
            options={
                'db_table': 'infocultura_event_seat',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('event', 'section_label', 'row_label', 'seat_label'), name='unique_event_section_row_seat_label'), models.UniqueConstraint(condition=models.Q(('eventbrite_seat_id__isnull', False)), fields=('event', 'eventbrite_seat_id'), name='unique_event_eventbrite_seat_id'), models.UniqueConstraint(condition=models.Q(('eventbrite_attendee_id__isnull', False)), fields=('event', 'eventbrite_attendee_id'), name='unique_event_eventbrite_attendee_id')],
            },
        ),
    ]
