# Generated by Django 5.1.6 on 2026-06-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infocultura', '0007_adminauditlog_book_category_clubregistration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventseat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='eventseatsyncissue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='venuelayout',
            options={'managed': False},
        ),
    ]
